[package]
name = "faststr"
version = "0.2.10"
authors = ["Volo Team <volo@cloudwego.io>"]
edition = "2021"
description = "Faststr is a string library that reduces the cost of clone."
repository = "https://github.com/volo-rs/faststr"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["string", "str", "volo"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
serde = { version = "1", optional = true, default_features = false }
redis = { version = "0.23", optional = true, default_features = false }
itoa = { version = "1", optional = true }

[dev-dependencies]
static_assertions = { version = "1" }

[features]
default = ["std"]
std = ["serde/std"]
redis = ["dep:redis", "itoa"]
